### ISSUE TITLE
Programmatic Access returns a Non-Writable Stream?

### ISSUE THREAD

**Issue by swaj** [MechanicalHuman/dev-bunyan-pretty#2]
I'm attempting to use the programmatic interface in version 2.1.2.  Here's some sample code:

```js
const bunyan = require('bunyan');
const pretty = require('@mechanicalhuman/bunyan-pretty');

const streamArray = [];

streamArray.push({
    name: 'stdout',
    level: 'info',
    stream: pretty(process.stdout, { timeStamps: false })
});

const logger = bunyan.createLogger({
    name: 'my:logger',
    streams: streamArray
});

logger.info('test');
```

When this code is executed, the following exception is thrown:

```
assert.js:43
  throw new errors.AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: "stream" stream is not writable: [Function: pretty]
    at Logger.addStream (/Users/scott/dev/test-project/node_modules/bunyan/lib/bunyan.js:580:16)
    at /Users/scott/dev/test-project/node_modules/bunyan/lib/bunyan.js:470:18
    at Array.forEach (<anonymous>)
    at new Logger (/Users/scott/dev/test-project/node_modules/bunyan/lib/bunyan.js:469:25)
    at Function.createLogger (/Users/scott/dev/test-project/node_modules/bunyan/lib/bunyan.js:1618:12)
    at Object.<anonymous> (/Users/scott/dev/test-project/test.js:12:23)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
```

It looks like the `pretty()` function isn't returning a writable stream anymore.

**Please note**:  This sample code works perfectly on version 2.0.8, but it fails on version 2.1.2.

**Comment by MechanicalHuman** [comment]
Ohh. 
I mistakenly merged a local branch meant to align the module with [Pino’s Prettifier API](http://getpino.io/#/docs/pretty?id=prettifier-api). 

I’m working on a hotfix to revert the main export to work as described in the readme

**Comment by MechanicalHuman** [comment]
Actually, can you please stick to the 2.0.8 until I write proper unit testing?

**Comment by swaj** [comment]
Sure thing.  I just wanted to let you know :)
